# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocking', '0002_auto_20161103_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocking.Language'),
        ),
    ]
